// generated by Fast Light User Interface Designer (fluid) version 1.0103

#include "main_win.h"
#include "cli.h"
int dispMode;
#include "doppel_config.h"

inline void MainWin::cb_r320MI_i(Fl_Menu_*, void*) {
  viewerResize(320, 240, false);
}
void MainWin::cb_r320MI(Fl_Menu_* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_r320MI_i(o,v);
}

inline void MainWin::cb_r640MI_i(Fl_Menu_*, void*) {
  viewerResize(640, 480, false);
}
void MainWin::cb_r640MI(Fl_Menu_* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_r640MI_i(o,v);
}

inline void MainWin::cb_r720MI_i(Fl_Menu_*, void*) {
  viewerResize(720, 480, false);
}
void MainWin::cb_r720MI(Fl_Menu_* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_r720MI_i(o,v);
}

inline void MainWin::cb_r290MI_i(Fl_Menu_*, void*) {
  viewerResize(290, 575, false);
}
void MainWin::cb_r290MI(Fl_Menu_* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_r290MI_i(o,v);
}

inline void MainWin::cb_rOtherMI_i(Fl_Menu_*, void*) {
  viewerResize(-1, -1, false);
}
void MainWin::cb_rOtherMI(Fl_Menu_* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_rOtherMI_i(o,v);
}

Fl_Menu_Item MainWin::menu_resButton[] = {
 {"360x240", 0,  (Fl_Callback*)MainWin::cb_r320MI, 0, 0, 0, 0, 14, 56},
 {"640x480", 0,  (Fl_Callback*)MainWin::cb_r640MI, 0, 0, 0, 0, 14, 56},
 {"720x480", 0,  (Fl_Callback*)MainWin::cb_r720MI, 0, 0, 0, 0, 14, 56},
 {"290x575", 0,  (Fl_Callback*)MainWin::cb_r290MI, 0, 0, 0, 0, 14, 56},
 {"Other...", 0,  (Fl_Callback*)MainWin::cb_rOtherMI, 0, 0, 0, 0, 14, 56},
 {0}
};
Fl_Menu_Item* MainWin::r320MI = MainWin::menu_resButton + 0;
Fl_Menu_Item* MainWin::r640MI = MainWin::menu_resButton + 1;
Fl_Menu_Item* MainWin::r720MI = MainWin::menu_resButton + 2;
Fl_Menu_Item* MainWin::r290MI = MainWin::menu_resButton + 3;
Fl_Menu_Item* MainWin::rOtherMI = MainWin::menu_resButton + 4;

inline void MainWin::cb_whiteCB_i(Fl_Check_Button*, void*) {
  if (whiteCB->value()) {
bkgColor[0] = 1;
bkgColor[1] = 1;
bkgColor[2] = 1;
}
else {
bkgColor[0] = 0;
bkgColor[1] = 0;
bkgColor[2] = 0;
}
viewer->invalidate();
viewer->redraw();
}
void MainWin::cb_whiteCB(Fl_Check_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_whiteCB_i(o,v);
}

inline void MainWin::cb_Save_i(Fl_Button*, void*) {
  saveView();
}
void MainWin::cb_Save(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

inline void MainWin::cb_Load_i(Fl_Button*, void*) {
  loadView();
}
void MainWin::cb_Load(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

inline void MainWin::cb_smButton_i(Fl_Button*, void*) {
  wfButton->color(FL_GRAY);
hwButton->color(FL_GRAY);
flButton->color(FL_GRAY);
smButton->color(FL_YELLOW);
displayMode(VM_SMOOTH);
wfButton->redraw();
hwButton->redraw();
flButton->redraw();
}
void MainWin::cb_smButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_smButton_i(o,v);
}

#include <FL/Fl_Pixmap.H>
static const char *idata_cube[] = {
"32 32 -162 1",
" \300\300\300!\17\16\25\"\202\200\377#\224\223\376$\230\227\377%\234\233\377&\
\242\241\377\'\243\242\377(\244\243\377)\255\254\377*\256\255\377+\260\257\
\377,\262\261\377-\260\257\375.\257\256\373/\263\262\377""0\264\263\377""1\
\272\271\377""2\273\272\377""3\304\303\377""4\322\321\373""5km\377""6kk\376""7\
jj\375""8ji\373""9ij\371:hg\366;ff\362<ll\377=ml\377>jj\371?ii\370@ij\370""Aff\
\360""Bmm\377""Cii\366""Dhh\364""Enn\376""Fop\377Gsr\377Hoo\370Itu\377Juu\377K\
vw\377Lpp\362Mxz\377Njj\342Oyy\377Pvw\370Qzz\375Rtt\360Sxy\367T}~\377U{{\371V\
\200\200\377W||\370X||\365Y\203\203\377Z\204\204\377[\205\205\377\\\177\177\
\364]\206\207\377^\203\204\371_\210\210\377`\203\203\366""a\210\210\375""b\
\212\212\375""c\210\210\372""d\216\216\377""e\216\216\375""f\220\221\377g\217\
\220\376h\221\221\377i\222\222\377j\223\223\377k\224\224\377l\225\225\377m\t\t\
\17n\234\234\377o\241\241\377p\241\242\377q\242\243\377r\245\245\377s\247\247\
\377t\250\250\377u\251\251\377v\254\254\377w\255\255\377x\255\256\377y\256\
\256\377z\260\260\377{\261\261\377|\261\262\377}\250\250\362~\262\262\377\177\
\261\261\376\200\254\254\366\201\263\263\377\202\264\264\377\203\264\265\377\
\204\260\260\371\205\265\265\377\206\266\266\377\207\266\267\377\210\267\267\
\377\211\267\270\377\212\270\270\377\213\270\271\377\214\271\271\377\215\272\
\272\377\216\273\273\377\217\273\274\377\220\274\275\377\221\275\275\377\222\
\275\276\377\223\274\274\376\224\277\277\377\225\300\300\377\226\301\301\377\
\227\303\303\377\230\304\304\377\231\305\305\377\232\311\311\377\233\314\314\
\377\234\316\316\377\235\303\303\362\236\317\317\377\237\320\320\377\240\322\
\322\377\241\323\323\377\242\321\321\375\243\317\317\372\244\316\316\371\245\
\324\324\377\246\323\323\376\247\320\320\373\250\315\315\367\251\314\314\366\
\252\313\313\364\253os\373\254\234\236\377\255\262\264\377\256\275\277\377\
\257\301\303\377\260\302\304\377\261\304\305\377\262\316\317\377\263\321\322\
\377\264\322\323\377\265\323\324\377\266\305\306\357\267\323\324\376\270\13\f\
\23\271\5\6\t\272\2\3\3\273\0\2\1\274\0\1\0\275\1\1\0\276\1\0\0\277\0\0\0\300\
\277\277\277\301\2\2\2",
"                                ",
"                                ",
"                                ",
"                                ",
"          \277\277\277\277\277\277\277\275\276\277\277\277\277\277\277\277\
\277\277\277   ",
"         \277\245\245\245\245\245\245""4\250\252\251\247\246\245\267\244\266\
\235>\277   ",
"        \277\245\245\245\245\245\245\245\245\245\265\245\245\245\245\245\262\
\223^@\277   ",
"       \277\245\245\245\245\245\245\245\245\245\245\245\245\245\241\237\232\
\214\254S>\277   ",
"      \277\245\245\245\245\245\245\245\245\265\241\241\241\240\237\233\231""1\
sgP:\301   ",
"     \277\243\242\241\264\263\262\236\236\262\234\234\234\234\233\232""32)%cR\
:\271   ",
"    \277\200\204\212\216\256\224\226\257\260\230\230\261\231\231\227\225\215+\
\'#`R:\270   ",
"    \277}{|~/\205\207\213\214\215\217\220\222\221\217\212,tne\\R:!   ",
"    \277.{{{{||,~\255\203\210\212\211\206\201*($bXR:m   ",
"    \277{{{{{{{{{{|/0\202\201{v&l_UE:\272   ",
"    \277{{{{{{{{{{{{|||{vok]QH:\276   ",
"    \277{{{{{{{{{{{{{{{{voj[OE:\277   ",
"    \277{{{{{{{{{{{{{{{{voiZK5?\277   ",
"    \277{{{{{{{{{{{{{{{{vohYI=;\277   ",
"    \277{{{{{{{{{{{{{{{{vph\"J<A\275   ",
"    \277{{{{{{{{{{{{{{{{xqhVG<:\273   ",
"    \277{{{{{{{{{{{{{{{{zrfTF<8\274   ",
"    \277{{{{{{{{{{{{{{{{{udMB76\277   ",
"    \277{{{{{{{{{{{{{{{{{wa\253""C6\277    ",
"    \277{{{{{{{{{{{{{{{{{xW9D\277     ",
"    \277{{{{{{{{{{{{{{{{{yL9\277\300     ",
"    \277{{{{{{{{{{{{{{{{{-N\277       ",
"    \277{{{{{{{{{{{{{{{{{\177\277        ",
"    \277\277\277\277\277\277\277\277\277\277\277\277\277\277\277\277\277\277\
\277         ",
"                                ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_cube(idata_cube);

inline void MainWin::cb_flButton_i(Fl_Button*, void*) {
  wfButton->color(FL_GRAY);
hwButton->color(FL_GRAY);
flButton->color(FL_YELLOW);
smButton->color(FL_GRAY);
displayMode(VM_FLAT | VM_WF_ON);
wfButton->redraw();
hwButton->redraw();
smButton->redraw();
}
void MainWin::cb_flButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_flButton_i(o,v);
}

static const char *idata_cube1[] = {
"32 32 -5 1",
" \300\300\300!\0\0\0\"kk\377#\261\261\377$\324\324\377",
"                                ",
"                                ",
"                                ",
"                                ",
"         !!!!!!!!!!!!!!!!!!!    ",
"        !$$$$$$$$$$$$$$$$$\"!    ",
"       !$$$$$$$$$$$$$$$$$\"\"!    ",
"      !$$$$$$$$$$$$$$$$$\"\"\"!    ",
"     !$$$$$$$$$$$$$$$$$\"\"\"\"!    ",
"    !$$$$$$$$$$$$$$$$$\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"\"!    ",
"   !##################\"\"\"\"!     ",
"   !##################\"\"\"!      ",
"   !##################\"\"!       ",
"   !##################\"!        ",
"   !##################!         ",
"   !!!!!!!!!!!!!!!!!!!          ",
"                                ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_cube1(idata_cube1);

inline void MainWin::cb_hwButton_i(Fl_Button*, void*) {
  wfButton->color(FL_GRAY);
hwButton->color(FL_YELLOW);
flButton->color(FL_GRAY);
smButton->color(FL_GRAY);
displayMode(VM_HIDDEN_LINE);
wfButton->redraw();
flButton->redraw();
smButton->redraw();
}
void MainWin::cb_hwButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_hwButton_i(o,v);
}

static const char *idata_cube2[] = {
"32 32 -2 1",
" \300\300\300!\0\0\0",
"                                ",
"                                ",
"                                ",
"                                ",
"         !!!!!!!!!!!!!!!!!!!    ",
"        !                 !!    ",
"       !                 ! !    ",
"      !                 !  !    ",
"     !                 !   !    ",
"    !                 !    !    ",
"   !!!!!!!!!!!!!!!!!!!     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !     !    ",
"   !                 !    !     ",
"   !                 !   !      ",
"   !                 !  !       ",
"   !                 ! !        ",
"   !                 !!         ",
"   !!!!!!!!!!!!!!!!!!!          ",
"                                ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_cube2(idata_cube2);

inline void MainWin::cb_wfButton_i(Fl_Button*, void*) {
  wfButton->color(FL_YELLOW);
hwButton->color(FL_GRAY);
flButton->color(FL_GRAY);
smButton->color(FL_GRAY);
displayMode(VM_WIREFRAME);
hwButton->redraw();
flButton->redraw();
smButton->redraw();
}
void MainWin::cb_wfButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_wfButton_i(o,v);
}

static const char *idata_cube3[] = {
"32 32 -2 1",
" \300\300\300!\0\0\0",
"                                ",
"                                ",
"                                ",
"                                ",
"         !!!!!!!!!!!!!!!!!!!    ",
"        !!                !!    ",
"       ! !               ! !    ",
"      !  !              !  !    ",
"     !   !             !   !    ",
"    !    !            !    !    ",
"   !!!!!!!!!!!!!!!!!!!     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !           !     !    ",
"   !     !!!!!!!!!!!!!!!!!!!    ",
"   !    !            !    !     ",
"   !   !             !   !      ",
"   !  !              !  !       ",
"   ! !               ! !        ",
"   !!                !!         ",
"   !!!!!!!!!!!!!!!!!!!          ",
"                                ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_cube3(idata_cube3);

inline void MainWin::cb_rsButton_i(Fl_Button*, void*) {
  rsButton->color(FL_YELLOW);
rlButton->color(FL_GRAY);
rlButton->redraw();
viewer->controlMode = 0;
}
void MainWin::cb_rsButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_rsButton_i(o,v);
}

static const char *idata_rot[] = {
"32 32 -5 1",
" \300\300\300!\0\0\0\"kk\377#\261\261\377$\324\324\377",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"            !!!!!!!!!!!!!!!!!   ",
"           !$$$$$$$$$$$$$$$!!   ",
"          !$$$$$$$$$$$$$$$!\"!   ",
"         !$$$$$$$$$$$$$$$!\"\"!   ",
"        !$$$$$$$$$$$$$$$!\"\"\"!   ",
"       !!!!!!!!!!!!!!!!!\"\"\"\"!   ",
"       !###############!\"\"\"\"!   ",
"       !###############!\"\"\"\"!   ",
"    !  !###############!\"\"\"\"!   ",
"    !! !###############!\"\"\"\"!   ",
"  !!!!!!###############!\"\"\"!!!  ",
" !  !! !###############!\"\"\"\"! ! ",
"!   !  !###############!\"\"\"\"!  !",
"!      !###############!\"\"\"\"!  !",
" !     !###############!\"\"\"\"! ! ",
"  !!   !###############!\"\"\"\"!!  ",
"    !!!!!!!!##########!!!!!!    ",
"       !####!!!!!!!!!!#!\"\"!     ",
"       !###############!\"!      ",
"       !###############!!       ",
"       !!!!!!!!!!!!!!!!!        ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_rot(idata_rot);

inline void MainWin::cb__i(Fl_Button*, void*) {
  viewer->screenshot();
}
void MainWin::cb_(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb__i(o,v);
}

static const char *idata_camera[] = {
"32 32 -11 1",
" \300\300\300!\377\377\377\"\314\314\314#\356\356\356$\335\335\335%\273\273\
\273&\252\252\252\'\210\210\210(www)UUU*\0\0\0",
"                                ",
"                                ",
"     ****                       ",
"   ***#%*********************   ",
"  *\"\"))))\"\"\"%%%%%&&&&&&&&&&&&*  ",
"  ****************************  ",
" *))))))))))))))))))))))))))))* ",
" *)))))))))*********))))))))))* ",
" *)))))))**\'\'\'\'\'((((**))))))))* ",
" *))))))*%&&*******(((*)))))))* ",
" *)))))*\"%**!!!!!!!**((*))))))* ",
" *)))))*\"*!!\'*****\'!!*(*))))))* ",
" *))))*%*!!**\"\"\"\"\"**!!*(*)))))* ",
" *))))**!\"*\"\"$$$$$\"\"*\"!**)))))* ",
" *)))**!&*\"\"$!!##$\"\"\"*&!**))))* ",
" *)))**!*\"\"#!!$\"\"\"\"\"\"\"*!**))))* ",
" *)))*!*\"\"#!!\"\"\"\"\"\"\"\"\"&*!*))))* ",
" *)))*!*\"$!#\"\"\"\"\"\"\"\"%%%*!*))))* ",
" *)))*!*\"##$\"\"\"\"\"\"\"\"%%&*!*))))* ",
" *)))*!*\"$$\"\"\"\"\"\"\"\"\"%%&*!*))))* ",
"  ****!*\"$\"\"\"\"\"\"\"\"\"\"%&&*!*****  ",
"     *!*\"$\"\"\"\"\"\"\"\"\"%%&\'*!*      ",
"      *!*\"\"\"\"\"\"\"\"\"%%&\'*!*       ",
"      *!&*\"\"\"\"\"%%%%&\'*&!*       ",
"       *!\"*\"\"\"%%%&&\'*\"!*        ",
"        *!!**&%&&&**!!*         ",
"         *!!\'*****\'!!*          ",
"          **!!!!!!!**           ",
"            *******             ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_camera(idata_camera);

inline void MainWin::cb_rlButton_i(Fl_Button*, void*) {
  rlButton->color(FL_YELLOW);
rsButton->color(FL_GRAY);
rsButton->redraw();
viewer->controlMode = 1;
}
void MainWin::cb_rlButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_rlButton_i(o,v);
}

static const char *idata_rot1[] = {
"32 32 -6 1",
" \300\300\300!\0\0\0\"\240\240\244#\377\373\360$\377\375\373%zzz",
"                                ",
"                                ",
"                                ",
"                                ",
"             !!!!!!             ",
"           !!######!!           ",
"          !##########!          ",
"         !######$$####!         ",
"         !#######$$###!         ",
"        !#########$$###!        ",
"        !##########$###!        ",
"        !##########$###!        ",
"        !##############!        ",
"    !    !############!         ",
"    !!   !############!         ",
"  !!!!!   !##########!     !!!  ",
" !  !!     !########!         ! ",
"!   !       !######!           !",
"!           !######!           !",
" !          !!!!!!!!          ! ",
"  !!        !%%%%\"\"!        !!  ",
"    !!!!!!! !\"\"\"\"\"\"! !!!!!!!    ",
"           !!!!!!!!!!           ",
"            !\"\"\"\"\"\"!            ",
"            !%%%%\"\"!            ",
"            !\"\"\"\"\"\"!            ",
"             !!!!!!             ",
"               !!               ",
"                                ",
"                                ",
"                                ",
"                                "
};
static Fl_Pixmap image_rot1(idata_rot1);

inline void MainWin::cb_1_i(Fl_Button*, void*) {
  viewer->home();
viewer->redraw();
}
void MainWin::cb_1(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_1_i(o,v);
}

static const char *idata_home[] = {
"32 32 -15 1",
" \300\300\300!\377\314\0\"\377""ff#\377\377\377$\314\0\0%\231\231\314&\231""3\
\0\'f\0\0(\335\0\0)\210\0\0*U\0\0+D\0\0,\335\335\335-\210\210\210.\0\0\0",
"                                ",
"                                ",
"                .               ",
"               .\".              ",
"              .()*.             ",
"             .\"((().  $$\'       ",
"            .()))))*. $\'\'       ",
"           .\"((((((().$\'+       ",
"          .()))))))))*.\'+       ",
"         .\"((((((((((().+       ",
"        .()))))))))))))*.       ",
"       .\"((((((((((((((().      ",
"      .()))))))))))))))))*.     ",
"     .\"((((((((((((((((((().    ",
"    .........................   ",
"       .-----------------.      ",
"       .#.....,,,,,.....-.      ",
"       .#.%%#.,,,,,.%%#.-.      ",
"       .#.%##.,,,,,.%##.-.      ",
"       .#.%#%.,,,,,.%#%.-.      ",
"       .#.%%%.,,,,,.%%%.-.      ",
"       .#.....,,,,,.....-.      ",
"       .#,,,,,,,,,,,,,,,-.      ",
"       .#,,,,,.....,,,,,-.      ",
"       .#,,,,,.&&&.,,,,,-.      ",
"       .#,,,,,.&&&.,,,,,-.      ",
"       .#,,,,,.&&!.,,,,,-.      ",
"       .#,,,,,.&&!.,,,,,-.      ",
"       .#,,,,,.&&&.,,,,,-.      ",
"       .#,,,,,.&&&.,,,,,-.      ",
"       ...................      ",
"                                "
};
static Fl_Pixmap image_home(idata_home);

inline void MainWin::cb_videoCB_i(Fl_Check_Button*, void*) {
  viewerResize(720, 480, videoCB->value() != 0);
}
void MainWin::cb_videoCB(Fl_Check_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_videoCB_i(o,v);
}

inline void MainWin::cb_RIB_i(Fl_Button*, void*) {
  viewer->saveRIB();
}
void MainWin::cb_RIB(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_RIB_i(o,v);
}

inline void MainWin::cb_bSkelButton_i(Fl_Button*, void*) {
  showSkel = !showSkel;
if (showSkel)
  bSkelButton->color(FL_YELLOW);
else
  bSkelButton->color(FL_GRAY);
bSkelButton->redraw();
redrawV();
}
void MainWin::cb_bSkelButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_bSkelButton_i(o,v);
}

static const char *idata_body[] = {
"32 32 -3 1",
" \300\300\300!\377\0\0\"\0\0\0",
"                                ",
"               \"                ",
"              \"!\"               ",
"              \"!\"               ",
"              \"!\"               ",
"              \"!\"               ",
"              \"!\"               ",
"          \"\"   \"   \"\"           ",
"         \"!!\" \"!\" \"!!\"          ",
"        \"!\"\"!\"\"!\"\"!\"\"!\"         ",
"       \"!\"  \"!\"!\"!\"  \"!\"        ",
"      \"!\"    \"\"!\"\"    \"!\"       ",
"      \"!\"     \"!\"     \"!\"       ",
"      \"!\"     \"!\"     \"!\"       ",
"      \"!\"     \"!\"     \"!\"       ",
"     \"!\"      \"!\"      \"!\"      ",
"    \"!\"      \"\"!\"\"      \"!\"     ",
"     \"      \"!!\"!!\"      \"      ",
"           \"!\"\" \"\"!\"            ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"            \"     \"             ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"           \"!\"   \"!\"            ",
"          \"\"!\"   \"!\"\"           ",
"         \"!!\"     \"!!\"          ",
"          \"\"       \"\"           "
};
static Fl_Pixmap image_body(idata_body);

inline void MainWin::cb_bTemplateButton_i(Fl_Button*, void*) {
  showTemplate = !showTemplate;
if (showTemplate)
  bTemplateButton->color(FL_YELLOW);
else
  bTemplateButton->color(FL_GRAY);
bTemplateButton->redraw();
redrawV();
}
void MainWin::cb_bTemplateButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_bTemplateButton_i(o,v);
}

static const char *idata_body1[] = {
"32 32 -8 1",
" \300\300\300!\367\367\367\"\336\336\336#\265\265\265$\214\255\377%k\214\377&\
Js\377\'\0\0\0",
"             \'\'\'\'\'              ",
"            \'!$$$\"\'             ",
"           \'$%\"\"\"%%\'            ",
"           \'$%\"\"\"%&\'            ",
"           \'$%\"\"\"%&\'            ",
"            \'\"%%&#\'             ",
"             \'%%&\'              ",
"          \'\'\'\'\"\"\"\'\'\'\'           ",
"         \'!%%%\"\"\"%%%\"\'          ",
"        \'$%\"\"\"%%%\"\"\"%%\'         ",
"       \'$%\'\"\"\"%%%\"\"\"\'%%\'        ",
"      \'!\"\' \'!\"%%%\"#\' \'!\"\'       ",
"      \'!\"\' \'$%\"\"\"%&\' \'!\"\'       ",
"      \'$%\' \'$%\"\"\"%&\' \'$%\'       ",
"      \'$%\' \'$%\"\"\"%&\' \'$%\'       ",
"     \'\"\"\'  \'!\"%%%\"#\'  \'\"\"\'      ",
"    \'\"\"\'   \'!\"%%%\"#\'   \'\"#\'     ",
"     \'\'    \'!\"%%%\"\"\'    \'\'      ",
"           \'$%\"\"\"%&\'            ",
"           \'$%\'\'\'%&\'            ",
"           \'!\"\' \'!\"\'            ",
"           \'!\"\' \'!\"\'            ",
"           \'$%\' \'%%\'            ",
"           \'$%\' \'%%\'            ",
"           \'!\"\' \'!\"\'            ",
"           \'!\"\' \'!\"\'            ",
"           \'$%\' \'%%\'            ",
"           \'$%\' \'%%\'            ",
"           \'!\"\' \'!\"\'            ",
"          \'\'!\"\' \'!\"\'\'           ",
"         \'%%\"\"\' \'!\"%%\'          ",
"          \'\'\'\'  \'\'\'\'\'           "
};
static Fl_Pixmap image_body1(idata_body1);

inline void MainWin::cb_bDefButton_i(Fl_Button*, void*) {
  showDef = !showDef;;
if (showDef)
  bDefButton->color(FL_YELLOW);
else
  bDefButton->color(FL_GRAY);
bDefButton->redraw();
redrawV();
}
void MainWin::cb_bDefButton(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_bDefButton_i(o,v);
}

static const char *idata_body2[] = {
"32 32 -6 1",
" \300\300\300!\367\367\367\"\336\336\336#\324\320\310$\265\265\265%\0\0\0",
"             %%%%%              ",
"            %!!!\"\"%             ",
"           %!!\"\"\"\"\"%            ",
"           %!\"\"\"\"\"$%            ",
"           %!\"\"\"\"\"$%            ",
"            %!\"\"\"$%             ",
"          %%#%!\"$%#%%           ",
"         %!!%%\"\"$%%\"$%          ",
"        %!\"!\"$\"\"\"$\"\"!$%         ",
"       %!\"\"\"\"\"$\"$\"\"\"\"\"$%        ",
"      %!\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"$%       ",
"      %!\"\"%!\"\"\"\"\"\"\"$%%!\"%       ",
"      %!\"% %!\"\"\"\"\"$% %!\"%       ",
"      %!\"% %!$$\"$$$% %!\"%       ",
"      %\"\"% %!\"\"\"\"$$% %!\"%       ",
"     %\"\"\"% %\"\"\"\"\"\"$% %\"\"$%      ",
"    %\"\"\"%  %\"\"\"$\"\"$%  %\"\"$%     ",
"     %%%   %!\"\"\"\"\"\"%   %%%      ",
"           %!\"\"\"\"\"\"%            ",
"           %!\"%%%!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"           %!\"% %!\"%            ",
"          %%!\"% %!\"%%           ",
"         %!\"\"\"% %!\"\"$%          ",
"          %%%%  %%%%%           "
};
static Fl_Pixmap image_body2(idata_body2);

inline void MainWin::cb_lightingCB_i(Fl_Check_Button*, void*) {
  lightingEnabled = (lightingCB->value() != 0);
if (!lightingEnabled)
	dispMode = dispMode & (~(VM_SURF_FLAT | VM_SURF_SMOOTH));
redrawV();
}
void MainWin::cb_lightingCB(Fl_Check_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_lightingCB_i(o,v);
}

inline void MainWin::cb_cmdInput_i(Fl_Input*, void*) {
  processCommand(cmdInput->value());
presetMB->add(fixLabel(cmdInput->value()), "", (Fl_Callback*)cb_procLabel, strdup(cmdInput->value()));
}
void MainWin::cb_cmdInput(Fl_Input* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_cmdInput_i(o,v);
}

inline void MainWin::cb_Run_i(Fl_Button*, void*) {
  char *fname = fl_file_chooser(
	"Run script...",
	"*.txt",
	NULL);
if (fname) {
  processFile(fname);
};
}
void MainWin::cb_Run(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_Run_i(o,v);
}

MainWin::MainWin() {
  Fl_Window* w;
  { Fl_Window* o = window = new Fl_Window(800, 576, "Doppel");
    w = o;
    o->user_data((void*)(this));
    { Fl_Menu_Button* o = resButton = new Fl_Menu_Button(0, 180, 160, 25, "360x240");
      o->menu(menu_resButton);
    }
    { Viewer* o = viewer = new Viewer(160, 0, 640, 575, "viewer");
      o->box(FL_DOWN_BOX);
      o->color(49);
      o->selection_color(49);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(56);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    { Fl_Box* o = sepBox = new Fl_Box(0, 205, 160, 5);
      o->box(FL_THIN_DOWN_FRAME);
    }
    { Fl_Check_Button* o = whiteCB = new Fl_Check_Button(0, 525, 25, 25, "White bkg");
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->callback((Fl_Callback*)cb_whiteCB);
    }
    { Fl_Button* o = new Fl_Button(0, 550, 80, 25, "Save view...");
      o->callback((Fl_Callback*)cb_Save);
    }
    { Fl_Button* o = new Fl_Button(80, 550, 80, 25, "Load view...");
      o->callback((Fl_Callback*)cb_Load);
    }
    { Fl_Button* o = smButton = new Fl_Button(120, 45, 40, 40);
      o->color(3);
      o->image(image_cube);
      o->callback((Fl_Callback*)cb_smButton);
    }
    { Fl_Button* o = flButton = new Fl_Button(80, 45, 40, 40);
      o->image(image_cube1);
      o->callback((Fl_Callback*)cb_flButton);
    }
    { Fl_Button* o = hwButton = new Fl_Button(40, 45, 40, 40);
      o->image(image_cube2);
      o->callback((Fl_Callback*)cb_hwButton);
    }
    { Fl_Button* o = wfButton = new Fl_Button(0, 45, 40, 40);
      o->image(image_cube3);
      o->callback((Fl_Callback*)cb_wfButton);
    }
    { Fl_Button* o = rsButton = new Fl_Button(40, 0, 40, 40);
      o->color(3);
      o->image(image_rot);
      o->callback((Fl_Callback*)cb_rsButton);
    }
    { Fl_Button* o = new Fl_Button(20, 90, 40, 40);
      o->image(image_camera);
      o->callback((Fl_Callback*)cb_);
    }
    { Fl_Button* o = rlButton = new Fl_Button(80, 0, 40, 40);
      o->image(image_rot1);
      o->callback((Fl_Callback*)cb_rlButton);
    }
    { Fl_Button* o = new Fl_Button(100, 90, 40, 40);
      o->image(image_home);
      o->callback((Fl_Callback*)cb_1);
    }
    { Fl_Check_Button* o = videoCB = new Fl_Check_Button(90, 525, 25, 25, "Video");
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->callback((Fl_Callback*)cb_videoCB);
    }
    { Fl_Button* o = new Fl_Button(60, 90, 40, 40, "RIB");
      o->callback((Fl_Callback*)cb_RIB);
    }
    { Fl_Button* o = bSkelButton = new Fl_Button(15, 135, 40, 40);
      o->image(image_body);
      o->callback((Fl_Callback*)cb_bSkelButton);
    }
    { Fl_Button* o = bTemplateButton = new Fl_Button(55, 135, 40, 40);
      o->image(image_body1);
      o->callback((Fl_Callback*)cb_bTemplateButton);
    }
    { Fl_Button* o = bDefButton = new Fl_Button(95, 135, 40, 40);
      o->image(image_body2);
      o->callback((Fl_Callback*)cb_bDefButton);
    }
    { Fl_Check_Button* o = lightingCB = new Fl_Check_Button(125, 10, 25, 25);
      o->down_box(FL_DIAMOND_DOWN_BOX);
      o->value(1);
      o->callback((Fl_Callback*)cb_lightingCB);
    }
    { Fl_Input* o = cmdInput = new Fl_Input(5, 440, 150, 25);
      o->callback((Fl_Callback*)cb_cmdInput);
    }
    { Fl_Button* o = new Fl_Button(5, 503, 150, 25, "Run script...");
      o->callback((Fl_Callback*)cb_Run);
    }
    { Fl_Menu_Button* o = presetMB = new Fl_Menu_Button(5, 472, 150, 25, "Preset commands");
    }
    o->end();
  }
  viewer->mainWin = this;
videoAspect = false;
cmdInput->when(FL_WHEN_ENTER_KEY|FL_WHEN_NOT_CHANGED);
ifstream in("cmds.txt");
if (in.good()) {
  char s[1024];
  while (in.good()) {
    in.getline(s, 1023);
    if (strlen(s) > 0) {
      presetMB->add(fixLabel(s), "", (Fl_Callback*)cb_procLabel, strdup(s));
    }
  }
  in.close();
}
}

void MainWin::viewerResize(int x, int y, bool video) {
  if (x < 0) {
 // ...
}
int newW = window->w() + x - viewer->w();
int newH = window->h() + y - viewer->h();
videoAspect = video;
window->resize(window->x(), window->y(), newW, newH);
updateResButton();
}

void MainWin::updateResButton() {
  static char str[80];
sprintf(str, "%dx%d", viewer->w(), viewer->h());
resButton->label(str);
}

void MainWin::displayMode(int mode) {
  dispMode = mode;
if (!lightingEnabled)
	dispMode = dispMode & (~(VM_SURF_FLAT | VM_SURF_SMOOTH));
viewer->redraw();
}

void MainWin::saveView() {
  char *fname = fl_file_chooser("L",
 "*.ca.txt",
 NULL);
if (fname == NULL)
 return;

ofstream out(fname);
if (!out.good()) {
  cout << "can't open " << fname << endl;
  return;
}
saveLoad.saveInstance(out, &viewer->camera);
out.close();
}

void MainWin::loadView() {
  char *fname = fl_file_chooser("L",
 "*.ca.txt",
 NULL);
if (fname == NULL)
 return;

ifstream in(fname);
if (!in.good()) {
  cout << "can't open " << fname << endl;
  return;
}
saveLoad.loadInstance(in, &viewer->camera);
in.close();
viewer->invalidate();
viewer->redraw();
}

void MainWin::cb_button(Fl_Button* o, void* v) {
  ((MainWin*)(o->parent()->user_data()))->cb_button_i(o,v);
}

inline void MainWin::cb_button_i(Fl_Button*o, void*) {
  int i;
for (i=0; i < tools.size(); i++)
 if (strcmp(tools[i]->name, o->label()) == 0) {
   tools[i]->show();
 }
}

void MainWin::addTool(Tool *tool) {
  tools.push_back(tool);
Fl_Button* o = new Fl_Button(10, 185 + 25*tools.size(), 135, 25, tool->name);
o->callback((Fl_Callback*)cb_button);
window->add(o);
}

void MainWin::cb_procLabel(Fl_Menu_*m, void*s) {
  processCommand((char*)s);
}

char * MainWin::fixLabel(const char *s) {
  static char fn[1024];
int i, i2 = 0;
for (i=0; i < 1023; i++) {
  if (s[i] == 0)
    break;
  if (s[i] == '/' || s[i] == '\\' || s[i] == '&' || s[i] == '_')
    fn[i2++] = '\\';
  fn[i2++] = s[i];
}
fn[i2] = 0;
return fn;
}
