// generated by Fast Light User Interface Designer (fluid) version 1.0103

#ifndef scUI_h
#define scUI_h
#include <FL/Fl.H>
#include "propui.h"
#include <FL/Fl_Window.H>
#include "tool.h"
#include "Fl/fl_file_chooser.h"
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Scroll.H>

class SCUI : public Tool {
public:
  SCUI();
  Fl_Window *scWindow;
private:
  inline void cb_scWindow_i(Fl_Window*, void*);
  static void cb_scWindow(Fl_Window*, void*);
public:
  Fl_Round_Button *showRep;
private:
  inline void cb_showRep_i(Fl_Round_Button*, void*);
  static void cb_showRep(Fl_Round_Button*, void*);
public:
  Fl_Round_Button *showSkinPts;
private:
  inline void cb_showSkinPts_i(Fl_Round_Button*, void*);
  static void cb_showSkinPts(Fl_Round_Button*, void*);
public:
  Fl_Value_Slider *replayVS;
private:
  inline void cb_replayVS_i(Fl_Value_Slider*, void*);
  static void cb_replayVS(Fl_Value_Slider*, void*);
public:
  Fl_Round_Button *showSCMesh;
private:
  inline void cb_showSCMesh_i(Fl_Round_Button*, void*);
  static void cb_showSCMesh(Fl_Round_Button*, void*);
  inline void cb_Edit_i(Fl_Button*, void*);
  static void cb_Edit(Fl_Button*, void*);
public:
  Fl_Round_Button *showSCSkel;
private:
  inline void cb_showSCSkel_i(Fl_Round_Button*, void*);
  static void cb_showSCSkel(Fl_Round_Button*, void*);
public:
  Fl_Window *skelWindow;
  Fl_Scroll *skelScroll;
private:
  inline void cb_Load_i(Fl_Button*, void*);
  static void cb_Load(Fl_Button*, void*);
  inline void cb_Save_i(Fl_Button*, void*);
  static void cb_Save(Fl_Button*, void*);
public:
  void show();
  virtual void drawGL();
  void showSkel();
  static void editCB(PropUI*);
};
#endif
